### ISSUE TITLE
IP address n/a

### ISSUE THREAD

**Issue by veloraptor** [jhubig/uebersicht-widget-fritzBoxPro#1]
and I have no clue why just n/a is there. How does the retrieval of the IP address work and any thoughts why it is not displayed here? Just a rough description but my hope is that you have a aha-effect ;-)
Thanks Peter

**Comment by jhubig** [comment]
Hey,

saw it also on my machine. I recently switched from cable to DSL. A fix is on the way. Thanks for the hint 😀 . Just download the bash script or download again the fritzBoxPro.widget.zip file.

Cheers,
Johannes
